# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/adapters/persistence/dbconfig/schemas/sqlite/schema.rs"

[migrations_directory]
dir = "migrations"
