version: '3'
services:
  podfetch:
    image: samuel19982/podfetch:latest
    user: ${UID:-1000}:${GID:-1000}
    ports:
      - "80:8000"
    volumes:
      - podgrab-podcasts:/app/podcasts
      - podgrab-db:/app/db
    environment:
      - POLLING_INTERVAL=60
      - SERVER_URL=http://localhost:80
      - DATABASE_URL=sqlite:///app/db/podcast.db

volumes:
    podgrab-podcasts:
    podgrab-db: